language: python
python:
  - "2.7"

install:
  - "pip install twisted"
  - "pip install requests"
  - "pip install python-dateutil"
  - "pip install feedparser"

script:
  - "trial plugins"
  - "trial utils"

notifications:
  irc:
    channels:
      - "irc.chalmers.it#platinumshrimp"
    use_notice: true
    skip_join: true
