language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

install:
  - "pip install requests"
  - "pip install requests-mock"
  - "pip install python-dateutil"
  - "pip install feedparser"
  - "pip install pyzmq"
  - "pip install irc"

script:
  - "python -m unittest discover -v"

notifications:
  irc:
    channels:
      - "ircs://irc.chalmers.it:9999/#platinumshrimp"
    use_notice: true
